# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: cf68d6cd9392a8db51203a372fc4c09172e0ebc478ec636076c1db76487c93d411b436605f957bfe137649a717e5f263466cddd37e6dc28c2c6f8a41d817df03

test:
  secret_key_base: ff2775b274caa341e89a24e42999f214b8d6e13f3db33b82042d24102e329660536aa99bfe0b4e04fea86f2c19dfa7324bfd945f1ec8fcca46297b35ef26e210

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
